import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Heart, Users, Brain, TrendingUp, Shield, Clock } from 'lucide-react';

export default function Home() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-600 via-blue-500 to-green-500 text-white py-20 px-4">
        <div className="max-w-6xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold mb-6">
            Your Journey to Better Health Starts Here
          </h1>
          <p className="text-xl md:text-2xl mb-8 text-blue-50">
            AI-powered personalized nutrition plans designed for your unique needs
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Link href="/register">
              <Button size="lg" className="bg-white text-blue-600 hover:bg-blue-50 px-8 py-6 text-lg">
                Get Started Free
              </Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline" className="border-white text-white hover:bg-white/20 px-8 py-6 text-lg">
                Sign In
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl font-bold text-center mb-12">Why Choose HealthyLife?</h2>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: <Brain className="w-12 h-12 text-blue-500" />,
                title: 'AI-Powered Plans',
                desc: 'Get personalized diet plans generated by advanced AI trained on medical research'
              },
              {
                icon: <Users className="w-12 h-12 text-green-500" />,
                title: 'Made for Seniors',
                desc: 'Simple, easy-to-use interface designed specifically for older adults'
              },
              {
                icon: <Heart className="w-12 h-12 text-red-500" />,
                title: 'Doctor Chatbot',
                desc: 'Get 24/7 health guidance from our AI doctor trained on medical literature'
              },
              {
                icon: <TrendingUp className="w-12 h-12 text-purple-500" />,
                title: 'Track Progress',
                desc: 'Monitor your weight, measurements, and health improvements over time'
              },
              {
                icon: <Shield className="w-12 h-12 text-orange-500" />,
                title: 'Medically Approved',
                desc: 'All plans follow evidence-based nutritional guidelines and medical standards'
              },
              {
                icon: <Clock className="w-12 h-12 text-indigo-500" />,
                title: 'Budget-Friendly',
                desc: 'Plans tailored to your budget with locally available, affordable ingredients'
              }
            ].map((feature, idx) => (
              <Card key={idx} className="border-0 shadow-lg hover:shadow-xl transition-shadow">
                <CardContent className="p-6 text-center">
                  <div className="flex justify-center mb-4">{feature.icon}</div>
                  <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                  <p className="text-gray-600">{feature.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-gradient-to-r from-blue-600 to-green-600 text-white">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl font-bold mb-6">Ready to Transform Your Health?</h2>
          <p className="text-xl mb-8">Join thousands who have improved their health with personalized nutrition</p>
          <Link href="/register">
            <Button size="lg" className="bg-white text-blue-600 hover:bg-blue-50 px-12 py-6 text-lg">
              Start Your Free Journey
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8 px-4">
        <div className="max-w-6xl mx-auto text-center">
          <p className="text-gray-400">© 2025 HealthyLife. Built with ❤️ for better health</p>
        </div>
      </footer>
    </div>
  );
}